### ISSUE TITLE
Two different client libraries for cloud-iot

### ISSUE THREAD

**Issue by oemergenc** [googleapis/java-iot#341]
Hi,

i am just getting started with cloud-iot. I am using java for development. 
Can anyone tell me how this two libraries relate to each other:

First one is the library from this repository:

*google-cloud-iot*
```
<dependency>
  <groupId>com.google.cloud</groupId>
  <artifactId>google-cloud-iot</artifactId>
  <version>1.1.10</version>
</dependency>
```

Second one can be found here https://github.com/googleapis/google-api-java-client-services/tree/master/clients/google-api-services-cloudiot/v1/1.31.0

*google-api-services-cloudiot*
```
<dependency>
  <groupId>com.google.apis</groupId>
  <artifactId>google-api-services-cloudiot</artifactId>
  <version>v1-rev20201110-1.31.0</version>
</dependency>
```

As far as i can see both are client libraries for development of the cloud-iot platform in java.
However i am confused which one i should use.

Any insights on this are greatly appreciated :) 

Thanks in advance.

**Comment by munkhuushmgl** [comment]
@oemergenc 
```
google-cloud-iot
``` 
is repo we will migrate all the samples in the future. 

I would suggest you use to 
```
google-api-services-cloudiot
```
since it has been maintained and supported for longest. it is client library based on Google's discovery format. 

Also, all samples are currently written in `google-api-services-cloudiot`

**Comment by oemergenc** [comment]
Hi,

thanks for your answer. 

Closing this for now.
